import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Navbar from './components/Navbar'
import Provider from './Provider'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface IProps{
  children: ReactNode;
  session:any
}

export default function RootLayout({
  children,session
}: IProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
        <Navbar />
        {children}
        </Provider>
        </body>
    </html>
  )
}
